### GET Locations
GET http://localhost:8080/api/v1/locations
Authorization: Bearer {{auth_token}}

### GET location by Id
GET http://localhost:8080/api/v1/locations/1
Authorization: Bearer {{auth_token}}

### POST location
POST http://localhost:8080/api/v1/locations
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "nome": "Rua dos devs",
  "imagem": "bairro.png",
  "email": "user@admin.com",
  "whatsapp": "(99) 99999-9999",
  "latitude": 12.34567,
  "longitude": 12.4567886,
  "cidade": "Vice City",
  "uf": "xx"
}

### PATCH location
PATCH http://localhost:8080/api/v1/locations/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "imagem": "bairro-dos-devs.png",
  "whatsapp": "(88) 88888-8888"
}

### DELETE location
DELETE http://localhost:8080/api/v1/locations/1
Authorization: Bearer {{auth_token}}