### GET ALL ITEMS
GET http://localhost:8080/api/v1/items

### GET BY ID
GET http://localhost:8080/api/v1/items/1

### POST ITEM
POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "titulo": "Plastico",
  "imagem": "plastico.png"
}

### UPDATE ITEM
PATCH http://localhost:8080/api/v1/items/1
Content-Type: application/json

{
  "titulo": "Papelão"
}

### DELETE ITEM
DELETE http://localhost:8080/api/v1/items/3